Introduce 2 buttons into FiveColors Screen
  and Extend UIAlertController Class to avoid warnings below:

ERROR: -[UIAlertController supportedInterfaceOrientations] was invoked recursively! Instead of using presentingViewController = <NavigationController: 0x116135c00>, will return super's value